services: 
  etcd:
      image: bitnami/etcd:latest
      container_name: etcd
      environment:
        - ETCD_NAME=etcd
        - ETCD_DATA_DIR=/etcd-data
        - ETCD_INITIAL_CLUSTER_STATE=new
        - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
        - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
        - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
        - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
        - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
        - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
        - ALLOW_NONE_AUTHENTICATION=yes
      volumes:
        - etcd-data:/etcd-data
      ports:
        - "2379:2379"
        - "2380:2380"
      restart: unless-stopped

volumes:
  etcd-data: